#!/usr/bin/env bash
(cd gateway-service && mvn compile jib:dockerBuild) &
(cd auth-service && mvn compile jib:dockerBuild) &
(cd user-service && mvn compile jib:dockerBuild) &
(cd book-service && mvn compile jib:dockerBuild) &
(cd discovery-service && mvn compile jib:dockerBuild) &
(cd listing-service && mvn compile jib:dockerBuild) &
(cd review-service && mvn compile jib:dockerBuild) &
(cd purchase-service && mvn compile jib:dockerBuild) &
wait
