server:
  port: 9191

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE-SIGNUP
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/signup
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
          filters:
            - name: JwtAuth
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        - id: BOOK-SERVICE
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/api/book/**
          filters:
            - name: JwtAuth
        - id: LISTING-SERVICE
          uri: lb://LISTING-SERVICE
          predicates:
            - Path=/api/listing/**
          filters:
            - name: JwtAuth

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true